"""empty message

Revision ID: 1d54eb8ea2fd
Revises: 9d3b184ebf98
Create Date: 2022-10-14 19:19:36.949854

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1d54eb8ea2fd"
down_revision = "9d3b184ebf98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
