"""empty message

Revision ID: 318a287c657c
Revises: 50d407f67333
Create Date: 2022-10-25 13:04:42.970361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "318a287c657c"
down_revision = "50d407f67333"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "category", type_="unique")
    # ### end Alembic commands ###
