"""empty message

Revision ID: 358e645b3dc2
Revises: 942c69067d9e
Create Date: 2022-10-15 12:46:46.507338

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "358e645b3dc2"
down_revision = "942c69067d9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
