"""empty message

Revision ID: 9d3b184ebf98
Revises: 17807b21612c
Create Date: 2022-10-14 19:17:57.171165

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d3b184ebf98"
down_revision = "17807b21612c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
