services:
  frontend:
    build:
      context: frontend/.
    ports:
      - 9000:9000
    domainname: frontend
  backend:
    build:
      context: backend/.
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend:/app
    domainname: backend
  reverseproxy:
    build:
      context: reverseproxy/.
    ports:
      - 80:80
