services:
  frontend:
    build:
      context: frontend/.
    ports:
      - 9000:9000
    domainname: frontend
  backend:
    build:
      context: backend/.
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend:/app
    domainname: backend
  reverseproxy:
    build:
      context: reverseproxy/.
    ports:
      - 80:80
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp
    ports:
      - 5432:5432
    volumes:
      - ./pgdata/pg:/var/lib/postgresql/data
